BBPBGLIB-1022 Model combiner
## Context

In order to start building models which can be a combination of mod/hoc file from a number of models, avoiding any name clash
we develop a script which combines them strictly following the rules as specified in a json config file.

## Scope

 - Initial implementation of `model_manager.py`
 - An example configuration showing the several cases
    - Using a plain prefix
    - Using a custom rename

# Example
```
(neurodamus-models)$ ./model_manager.py
Usage: ./model_manager.py <config_file>
```

Happy path
```
leite@bbpv2 ~/dev/neurodamus/neurodamus-models (model_combiner %)$ ./model_manager.py ./model_config.json
[INFO] Checking 'ALL'
[INFO] Building 'ALL'
[INFO]  - Processing common
[INFO]  - Processing neocortex
[INFO]    > Path neocortex/mod/v6/*.mod
[INFO]    > Path ['neocortex/mod/v5/DetGABAAB.mod', 'my_fancy_renamed_mod']
[INFO]   Path neocortex/hoc/*.hoc
[INFO]  - Processing hippocampus
[INFO]    > Path hippocampus/mod/*.mod
[INFO]   Path hippocampus/hoc/*.hoc
[INFO]  - Processing thalamus
[INFO]    > Path thalamus/mod/*.mod
[INFO]   Path thalamus/hoc/*.hoc
[INFO] Checking 'plasticity'
[INFO] Building 'plasticity'
[INFO]  - Processing neocortex
[INFO] Finished
```

Clash detection:
```
[INFO] Checking 'ALL'
[INFO] Building 'ALL'
[INFO]  - Processing common
[INFO]  - Processing neocortex
[INFO]    > Path neocortex/mod/v6/*.mod
[INFO]    > Path neocortex/mod/v5/DetGABAAB.mod
Traceback (most recent call last):
...
Exception: File already exists: build/ALL/mod/NCX_DetGABAAB.mod
```

----
Original commit: 1a56377b0e98ccf561b82f30e76ab3056b0efafe